FROM traktor-fibo-base
RUN ["apt-get","update"] 
RUN ["apt-get","upgrade","-y" , "--fix-missing"]
RUN apt-get update && apt-get -y install build-essential python python-pip px tcpdump libnetfilter-queue-dev iptables net-tools
RUN pip install --pre scapy[basic]
RUN pip install NetfilterQueue
COPY sniffing.py /app/sniffing.py


COPY start_interceptor.sh /app/start_interceptor.sh
COPY start_server.sh /app/start_server.sh
COPY wrapper_script.sh wrapper_script.sh
#ENTRYPOINT ["dotnet", "traktor-test-http-caller.dll"]
ENTRYPOINT ./wrapper_script.sh