FROM traktor-fibo-base
RUN ["apt-get","update"] 
RUN ["apt-get","upgrade","-y" , "--fix-missing"]
RUN apt-get update && apt-get -y install build-essential python3 python3-pip px tcpdump
RUN pip3 install --pre scapy[basic]
COPY sniffing.py /app/sniffing.py


COPY start_interceptor.sh /app/start_interceptor.sh
COPY start_server.sh /app/start_server.sh
COPY wrapper_script.sh wrapper_script.sh
#ENTRYPOINT ["dotnet", "traktor-test-http-caller.dll"]
ENTRYPOINT ./wrapper_script.sh