FROM traktor-fibo-base
RUN ["apt-get","update"] 
RUN ["apt-get","upgrade","-y" , "--fix-missing"]
RUN apt-get update && apt-get -y install build-essential python python-pip px tcpdump libnetfilter-queue-dev iptables net-tools
RUN pip install --pre scapy[basic]
RUN pip install NetfilterQueue
COPY sniffing.py /app/sniffing.py

COPY WebSocket.py /usr/local/lib/python2.7/dist-packages/scapy/layers/WebSocket.py
COPY wrapper_script.sh wrapper_script.sh
#ENTRYPOINT ["dotnet", "traktor-test-http-caller.dll"]
ENTRYPOINT ./wrapper_script.sh